name: Release LunarDate
run-name: ${{ github.actor }} releases LunarDate
on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:
    inputs:
      release_confirm:
        type: boolean
        description: Confirm release
        default: false
jobs:
  release-modules:
    if: github.event.inputs.release_confirm && github.event.pull_request.merged
    permissions: { contents: write }
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Log
        run: |
          echo ${{github.event.inputs.release_confirm}}
      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
